# Configuration file
# key = value
#--------------- VARIAVEIS DO PRÓPRIO GRUPO ---------------
MODO_MOCK=${MODO_MOCK}
EBSERH_PACIENTES_TESTE=${EBSERH_PACIENTES_TESTE}

#--------------- BANCO DE DADOS SQLITE ---------------
BD_URL=jdbc:sqlite:C:\\BASIS\\EBSERH\\testeTecnicoEBSERH\\pacientesEBSERH.sqlite
BD_USUARIO=
BD_SENHA=
BD_SIMULTANEO=3


#quarkus.log.category."io.quarkus".level=DEBUG
quarkus.log.category."io.quarkus".level=INFO

#smallrye.jwt.path.groups=realm_access/roles

