# Configuration file
# key = value
#--------------- VARIAVEIS DO PRÓPRIO GRUPO ---------------
MODO_MOCK=${MODO_MOCK}
EBSERH_PACIENTES_TESTE=${EBSERH_PACIENTES_TESTE}


#quarkus.log.category."io.quarkus".level=DEBUG
quarkus.log.category."io.quarkus".level=INFO

#smallrye.jwt.path.groups=realm_access/roles

